services:
  nextjs-app:
    image: vasath/msc-bda-cloud-assignment:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      appwrite-service:
        condition: service_healthy
    networks:
      - app-network

  appwrite-service:
    image: vasath/msc-bda-assignment-appwrite:latest
    container_name: appwrite-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./appwrite:/usr/src/code/appwrite:rw
      - ./initialize-appwrite.sh:/usr/src/code/initialize-appwrite.sh:ro
    environment:
      - _APP_ENVIRONMENT=production
      - _APP_PORT=80
      - _APP_PORT_HTTPS=443
      - _APP_SECRET_KEY=
      - _APP_HOSTNAME=localhost
      - _APP_CONSOLE_DOMAIN=localhost
      - _APP_SYSTEM_EMAIL=
      - _APP_LOGGING_PROVIDER=
    entrypoint: ["/bin/sh", "-c", "/usr/src/code/initialize-appwrite.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Authorization: Bearer super-secret-key", "http://localhost/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
